### ISSUE TITLE
Upgrade azure pipelines SDK to v2 

### ISSUE THREAD

**Issue by em-pe** [getindata/kedro-azureml#104]
Update Azure pipelines SDK to version 2.

Reference docs - https://learn.microsoft.com/en-us/azure/machine-learning/migrate-to-v2-execution-pipeline?view=azureml-api-2

**Comment by Lasica** [comment]
It's blocking next release, as current library/SDK misses binaries for ARM and fails to build on Mac.

**Comment by fdroessler** [comment]
I’m pretty sure we transitioned everything to the v2 sdk a while back see [here](https://github.com/getindata/kedro-azureml/blob/474ade08a7b22d757bc6fa251bd9cf6f98b312c1/CHANGELOG.md?plain=1#L26-L27). I also don’t see where we have a dependency on `azureml v1` atm?

Also according to pypi the latest version of azureml-dataprep-rslex 2.22.2 was published in January and I don’t think we had any issue recently on our side on mac machines. When are you encountering the issue?

**Comment by em-pe** [comment]
@fdroessler By Mac do you mean Intel or silicon based ones? I tried building it locally on my M1 but failed to do so because no ARM wheels are available for the mentioned library.

**Comment by tomasvanpottelbergh** [comment]
As @fdroessler said, we are already on the SDK v2 (which is the `azure-ai-ml` package instead of `azureml-core`. I get a different error, but indeed don't manage to install any version of `azureml-fsspec` on my M1. This issue seems to be tracked here: https://github.com/Azure/azure-sdk-for-python/issues/30593.

**Comment by Lasica** [comment]
Looks like misdiagnosis, thanks for the feedback. I'll close this issue, and maybe open another one to keep track of apple silicon azureml problem.
