### ISSUE TITLE
Add subscription to config

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [getindata/kedro-azureml#16]
Currently the Azure subscription ID needs to be provided with every invocation of the `kedro azureml run` command or needs to be set using the environment variable `AZURE_SUBSCRIPTION_ID`. I think it would be more consistent to add this to the configuration with an option to override via a CLI option.

Am I missing something or would a PR for this be welcome?

**Comment by marrrcin** [comment]
Initially we decided to have it in command line as it somehow "is" and "is not" a secret as per answer from https://stackoverflow.com/a/45663968/1955346 , so we decided to hide it from config. What's your opinion on that?
@em-pe  / @mwiewior maybe you can also chip in here.

**Comment by tomasvanpottelbergh** [comment]
Thanks for clarifying. To me the subscription ID is quite clearly not a secret as it doesn't allow you to authenticate or obtain any permissions, and is on the same level as the storage account name, resource group, ...

I can see why one would preferably not have this publicly available, but storing them in a repo should be fine. The native Azure ML `config.json` [also stores this information](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-environment#workspace).

**Comment by marrrcin** [comment]
OK, that's fine for us - you can create w PR for this :)
