### ISSUE TITLE
Is there anyway to debug individual nodes in the pipeline? 

### ISSUE THREAD

**Issue by sharansabi** [getindata/kedro-azureml#17]
![image](https://user-images.githubusercontent.com/14885988/194838555-20064eda-7870-4ccb-a0f0-12379ab6bd31.png)

I'm trying to recreate a project pipeline similar to the spaceflights tutorial you had on youtube, but I can't even get past the first node. I get this error and is a bit confused about where to start debugging it? In the documentation, I can't see where the plugin creates the azurml components or pipeline files so I can go in and debug what it is trying to do.

**Comment by em-pe** [comment]
Hi, given that the pipelines run kedro commands in a docker container you should be able to run the specific steps locally. 

1. Install docker locally
2. Run `docker exec -it <container> bash` to open shell in a container 
3. Run `cd /home/kedro && kedro azureml -e <environment> execute --pipeline=<kedro_pipeline> --node=<kedro_node>` to execute the step inside the container.

**Comment by marrrcin** [comment]
From the error message I can tell that there is something wrong with your docker image (maybe you haven't rebuilt it). There should be Kedro installed within this image. The plugin also assumes that the project will be stored in the `/home/kedro` directory which is default for the `kedro-docker` plugin.

**Comment by em-pe** [comment]
Good to hear it works! :)  I'm closing the issue now. Feel free to open new one if there are any more questions.
