### ISSUE TITLE
Docker build fail with useradd: UID 0 is not unique

### ISSUE THREAD

**Issue by ymsahala** [getindata/kedro-azureml#29]
Hi Guys, hope anyone can help on that. When I follow the quick start to build docker, it fails with below error:

`Step 7/14 : RUN groupadd -f -g ${KEDRO_GID} -o kedro_group && useradd -d /home/kedro -s /bin/bash -g ${KEDRO_GID} -u ${KEDRO_UID} kedro
 ---> Running in cd4c32215333
**useradd: UID 0 is not unique**
The command '/bin/sh -c groupadd -f -g ${KEDRO_GID} -o kedro_group && useradd -d /home/kedro -s /bin/bash -g ${KEDRO_GID} -u ${KEDRO_UID} kedro' returned a non-zero code: 4
`
![image](https://user-images.githubusercontent.com/48077264/200731638-d7e46e04-a082-45bf-bd9c-efa4ed166a31.png)

BTW, I'm using root account in Cent OS to run the command.

Thanks!

**Comment by marrrcin** [comment]
Default docker image used by `kedro docker` plugin is debian-based (https://hub.docker.com/_/python), so all of the commands used in the generated `Dockerfile` were implemented with debian in mind. If you've switched the base image to CentOS, you need to manage and prepare the Dockerfile on your own.

It's not an issue with this plugin as we have no influence on how you prepare your docker images.
