### ISSUE TITLE
kedro-azureml can't find environment version

### ISSUE THREAD

**Issue by eliorc** [getindata/kedro-azureml#32]
Hi, I'm using the new version `0.3.1` using the suggested azureml environments feature. 
I have successfully completed the steps for creating a docker image and creating an environment.
In my workspace under environment, I can see the created environment
![image](https://user-images.githubusercontent.com/17727283/202989620-254997e3-d008-4afd-9109-9f179e51a3fa.png)

Now, it is important to mention, I am not using VSCode, so I don't have the AzureML plugin installed, rather I am using PyCharm.

When trying to execute `kedro azureml run` (subscription ID is set as an environment variable), I get the error

> ValidationException: Failed to extract version when parsing asset kedrotesting-environment of type environments as arm id. Version must be provided.

When trying to execute `kedro azureml run --aml_env kedrotesting-environment`, I am getting the same error.

Only when I specify the environment version as well does it work, e.g. `kedro azureml run --aml_env kedrotesting-environment:1` works fine.

I assume this is not intended, and the expected behavior is that the latest version of the default environment will be used

Attaching the full stacktrace

[stacktrace.txt](https://github.com/getindata/kedro-azureml/files/10054331/stacktrace.txt)

**Comment by marrrcin** [comment]
That's expected, as you have to specify environment **with** version, as it's stated in the point 7 of the quickstart documentation:

> 7. Initialize Kedro Azure ML plugin, it requires the Azure resource names as stated above. Experiment name can be anything you like (as long as it’s allowed by Azure ML). The environment name is the name of the Azure ML Environment to be created in the next steps. You can use the syntax `<environment_name>@latest` for the latest version or `<environment-name>:<version>` for a specific version.

**Comment by eliorc** [comment]
Okay, thx
