### ISSUE TITLE
Azure Storage credentials for storing files from the data catalog

### ISSUE THREAD

**Issue by trojan03** [getindata/kedro-azureml#35]
Hi there,

how would you access the Azure Storage from the data catalog assuming that the storage to be accessed is other than the default one called temporary_storage? 
Is there any mechanism to achieve that? Thanks

**Comment by marrrcin** [comment]
Use standard Kedro's credentials mechanism with combination of fsspec (specifying the paths to Azure Storage as `abfs://`)
* https://kedro.readthedocs.io/en/stable/kedro_project_setup/configuration.html#credentials
* https://kedro.readthedocs.io/en/stable/data/data_catalog.html?highlight=azure#specify-the-location-of-the-dataset

**Comment by trojan03** [comment]
We ended up with using Azure KeyVault and Kedro's credentials mechanism
