### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by fdroessler** [getindata/kedro-azureml#6]
Hi thanks for releasing this plugin, I was working on something similar when I came across this on the kedro discord. I was just running the Quickstart and it seems like everything is working until actually running the job. It gets submitted alright but then on the first node I get the following error:

```
[2022-08-06 11:16:48Z] Job failed, job RunId is xxxxxxxxxxxxxxx. Error: {"Error"\n{"Code":"ServiceError","Severity":null,"Message":"AzureMLCompute job failed.
OrchestrateJobError: Failed to execute command group with error Got CommonRuntimeJobError from executing command: 
Docker container `xxxxxxxx-execution-wrapper` failed with status code `1` due to response error: 
None","MessageFormat":null,"MessageParameters":null,"ReferenceCode":null,"DetailsUri":null,"Target":null,"Details":
[],"InnerError":null,"DebugInfo":null,"AdditionalInfo":null},"Correlation":
{"operation":"xxxxxxx","request":"xxxxx"},"Environment":"switzerlandnorth","Location":"switzerlandnorth","
Time":"2022-08-06T11:16:48.1243444+00:00","ComponentName":"globaljobdispatcher"}
```

Have you come across this? Is it a configuration mistake on my side in the resource group, storage account or container registry? Or did I forgot something else?

<img width="711" alt="Screenshot 2022-08-06 at 13 24 30" src="https://user-images.githubusercontent.com/11539266/183246884-3b3af408-6e24-41df-ba1a-fbb73e82b259.png">

**Comment by marrrcin** [comment]
Hi!
Thanks for your interest in our plugin!

Could you please send the user_logs from the failed component? Without it it would be difficult to say what's the root cause. My blind guess would that it's sth related to permissions to the storage account, you might double verify it too.

**Comment by fdroessler** [comment]
Thanks for the quick response!
That is the thing, I don't even get the user_logs folder. Which makes me guess something went wrong during the "setup" rather than the actual execution. The only other thing I have is the execution_logs

```
[2022-08-05 22:29:08Z] ReuseHash: xxxxxx-xxxxx-
xxxxx+xxxxxxx=, JobDefinitionToHash: {"Configuration":
{"Command":"cd /home/kedro && kedro azureml -e local execute --pipeline=__default__ --
node=data_processing.preprocess_companies_node --az-
output=DatasetOutputConfig:data_processing_preprocessed_companies","UseAbsolutePath":false,"Framework":"Python","
Communicator":"None","Target":"cpu-cluster-2","OutputData":{"keys":
["data_processing_preprocessed_companies"],"values":[{"OutputLocation":{"Uri":
{"Path":"azureml://datastores/workspaceblobstore/paths/azureml/{name}/data_processing_preprocessed_companies/",
"IsFile":false},"Type":"UriFolder"},"Mechanism":"Mount"}]},"NodeCount":1,"CredentialPassthrough":false,"Environment":
{"Name":"CliV2AnonymousEnvironment","Version":"xxxxxxxxxx"},"History":
{"OutputCollection":true,"DirectoriesToWatch":["logs"],"EnableMLflowTracking":false},"ParallelTask":
{"MaxRetriesPerWorker":0,"WorkerCountPerNode":1},"BatchAi":{"NodeCount":0},"AmlCompute":
{"RetainCluster":false,"ClusterMaxNodeCount":1},"AISuperComputer":{"InstanceType":"D2",
"ImageVersion":"pytorch-1.7.0","Interactive":false,"EnableAzmlInt":true,"SLATier":"Standard"},"Tensorflow":
{"WorkerCount":0,"ParameterServerCount":0},"Mpi":{"ProcessCountPerNode":1},"Hdi":
{"YarnDeployMode":"None"},"ContainerInstance":{"CpuCores":2.0,"MemoryGb":3.5},"Docker":
{"UseDocker":true,"SharedVolumes":true,"ShmSize":"2g"},"GlobalJobDispatcher":
{"MyResourceOnly":false,"LowPriorityVMTolerant":true},"CommandReturnCodeConfig":
{"ReturnCode":"Zero"},"EnvironmentVariables":{"KEDRO_AZURE_RUNNER_CONFIG":"{\"temporary_storage\": 
{\"account_name\": \"spaceflight_1659738413671\", \"container\": \"spaceflightstore\"}, \"run_id\": 
\"xxxxxxxxx\", \"storage_account_key\": 
\"xxxxxxxx"}",
"AZUREML_PARAMETER_Node_Count":"1","AZUREML_PARAMETER_companies":"companies"},"DataBricks":
{"Workers":0,"MinimumWorkerCount":0,"MaxMumWorkerCount":0,
"SparkVersion":"4.0.x-scala2.11","NodeTypeId":"Standard_D3_v2","TimeoutSeconds":0}},
"SnapshotId":"xxxxxxx"}
[2022-08-05 22:29:08Z] Starting run in Execution Service
[2022-08-05 22:29:08Z] RunId:[xxxxxx] ParentRunId:[xxxxxxxxx] ComputeTarget:[AmlCompute]
[2022-08-05 22:29:09Z] Job is in progress. Execution status: Preparing.
[2022-08-05 22:29:09Z] Job is in progress. Execution status: Queued.
[2022-08-05 22:29:11Z] Job is in progress. Execution status: Queued.
[2022-08-05 22:29:18Z] Job is in progress. Execution status: Running.
```

But I'll also double check the permissions and names again.

**Comment by fdroessler** [comment]
hmm get the same result when creating a completely fresh AML Studio instance...

**Comment by marrrcin** [comment]
@fdroessler 
We've double checked this in our side (even with a fresh AML studio instance) and we're not able to replicate your issue.

If there are no `user_logs` it means that the container was not started at all, which could indicate some issue with image pulling.

Here is what you can do to verify this:
1. Re-built the docker image and push it to public docker hub
2. Update azureml.yml to point to your public image
3. Run the pipeline again.

Remember that any change in your pipeline needs to go through the docker rebuild cycle, because the plugin executes the docker image and local changes are not reflected in the AML pipelines if you don't push the updated images.

If the above will work, it means that there is some issue with IAM between your ACR and AML.

Also, you can carefully study end-to-end tests we have in this repo, which perform all of the steps from the quickstart and they pass successfully: https://github.com/getindata/kedro-azureml/blob/8770f6da4228d319af4ab486e29493526d44f616/.github/workflows/test.yml#L97

**Comment by marrrcin** [comment]
@fdroessler have you managed to resolve the issue?

**Comment by fdroessler** [comment]
Hi @marrrcin sorry for the late response, I had a busy few days. I tried your suggestion with the dockerhub option but unfortunately no dice.
When I am digging deeper into the AML error I came across the following:

```
Failed to fetch build details
NotFoundError: No builds exist for environment CliV2AnonymousEnvironment version xxxx.
Trace ID : 0477b759-4b25-90f9-
Client request ID : 7b6946cd-4dbf-9242-
```

I am not too used to AML yet but for me this looks like it might be something related to the environment creation on AML. I'll continue looking into it but just in case you have any ideas.

**Comment by fdroessler** [comment]
@marrrcin it is indeed a permission issue, I am still investigating it on the one account but I was able to get it running with no issues on completely different account. Once I figured out what the issue was I will post an update here so others can avoid it.

**Comment by marrrcin** [comment]
Awesome, thanks for the update!
