### ISSUE TITLE
Add support for load-version/load-versions

### ISSUE THREAD

**Issue by AlexandreOuellet** [getindata/kedro-azureml#62]
I run multiple time the same pipeline on AzureML (multiple experiments testing different parameters at the same time).  My pipeline is as follow : 
* Unversionned dataset is used as input in function x, which generates a versionned dataset
* That versionned dataset is used  as input in function y

Another way of looking at it, it looks like this :
unversionned dataset -> function x -> versionned dataset -> function y

I have the following timeline : 
1. Starts Run A, node x
2. Starts Run B, node x
3. Run B node x finishes, saves a versionned dataset
4. Run B node y starts with versionned dataset from step 3 (as expected)
5. Run A node x finishes, saves a versionned dataset
6. Run A node y starts *with versionned dataset from step 3* (unexpected, should start with versionned dataset generated at step 5)

The issue seems to stem from how the version ID is generated/transfered.  Instead of having a single version ID for the run, and transfering that version ID from node to node, each node generates its own version ID (or fetch the latest one).  That bug seems to happen with kedro also, but is easily fixed if I specify "--load-versions" in the CLI (which I can't with kedro azureml).  If I was able to specify --load-versions, I believe this bug would disappear (or I could manage to work around it).  Right now, I can't run the same pipeline in parallel with different parameters, I'd need to create a new pipeline with a different name (which doesn't make sense at all, I'm just running multiple experiment in parallel).

**Comment by marrrcin** [comment]
Hi @AlexandreOuellet , thanks for creating the issue.
Indeed, the `--load-versions` is missing from the current CLI. Moreover, even if it will be passed, current implementation does not propagate it. It should definitely be added to the plugin.
We're keen to accept the contribution on that part! Are you willing to create a PR with that? We can guide you through the implementation process.
If not, we will add it to our backlog, but without any specific estimates on the implementation time yet.

**Comment by marrrcin** [comment]
Actually, an update for you @AlexandreOuellet :
in the PR created by @tomasvanpottelbergh there is added support for exactly that https://github.com/getindata/kedro-azureml/pull/60/files#diff-b581001a106daa976944fadbd8c82928c83738a13c27264db1fd5d67ffbd39c3R212

So this should be covered after the PR will get merged.

**Comment by AlexandreOuellet** [comment]
The issue is 2 way actually.

The first issue is related to kedro directly (see https://github.com/kedro-org/kedro/issues/2694)

The 2nd is the --load-versions, which seems to be what you are referring.  I'm happy to close this issue as soon as the PR is merged.

Thanks!

**Comment by fdroessler** [comment]
@marrrcin this can be closed I think

**Comment by marrrcin** [comment]
Closed by #60
