### ISSUE TITLE
Update Pydantic Dependency Version

### ISSUE THREAD

**Issue by robertmcleod2** [getindata/kedro-azureml#96]
The Pydantic dependency version in this package is quite out of date, with kedro-azureml 0.7.0 depending on pydantic<1.10.0 and >=1.9.1. This is causing issues when working with other packages which have updated their pydantic version to latest (now 2.7.0). 

Could this dependency version be updated please?

**Comment by fdroessler** [comment]
Hi Robert there is already #95 that is addressing this. Hopefully that will be merged soon.

**Comment by robertmcleod2** [comment]
Hi @fdroessler, ah my bad I didn't see that. Great to hear!

**Comment by em-pe** [comment]
Hi @robertmcleod2  I just released v0.8.0 with this change.
